@(echo '> NUL
echo off)
setlocal enableextensions
set "THIS_PATH=%~f0"
set "PARAM_1=%~1"
PowerShell.exe -Command "iex -Command ((gc \"%THIS_PATH:`=``%\") -join \"`n\")"
exit /b %errorlevel%
-- この1つ上の行までバッチファイル
') | sv -Name TempVar
# 参考
# https://www.pg-fl.jp/program/tips/ps1bat.htm
# ここからPowerShellスクリプト
#
#############################################################
# csvファイルを開く
Add-Type -Assembly System.Windows.Forms
$csvfile1 = "./db/03_monster_map.csv"
$csvfile2 = "./db/06_map_portal.csv"

if( Test-Path $csvfile1 ) {
   $ro2 = import-csv $csvfile1 -Encoding UTF8 -Header "ID","NAME","MAP","type","count","time","random","notes","subMAP_No","subMAP" | Select-Object -Skip 1
}
else{
   [System.Windows.Forms.MessageBox]::Show('cant open csv file','error')
   exit
}

if( Test-Path $csvfile2 ) {
   $map = import-csv $csvfile2 -Encoding UTF8 -Header "ID","MAP_NAME","KANA","city","portal","map_in","dun_in","Fld_Dun_MD","delete","BGM","BGM_title","country","area","pass","quest","party","zeny","time_limit","CT","re_Try","notes","short_NAME","sNAME_KANA" | Select-Object -Skip 1
}
else{
   [System.Windows.Forms.MessageBox]::Show('cant open csv file','error')
   exit
}

#############################################################
# マップ名を抽出
# やべえ位遅い、リアルに5秒位かかる
#foreach($work in $ro2){ `
#   foreach($work2 in $map){ `
#      if( $work.MAP -match $work2.ID ){ `
#          $work.MAP = $work2.MAP_NAME `
#      } `
#   } `
#} `
#
#############################################################
# ↑の高速化
# 地獄のようなifブロック生成
#foreach( $temp in $maplist ){
#   "   elseif( `$work.MAP -eq `"{0}`" ) {{ `$work.MAP = `"{1}`" }}" -f $temp.ID,$temp.NAME >> cachemap.txt
#}
#
# ↓地獄のようなifブロック
Measure-Command{ `
foreach( $work in $ro2 ){  `
       if( $work.MAP -eq "pvp_y_room" ) { $work.MAP = "PvP : ナイトメアモード控え室" }
   elseif( $work.MAP -eq "pvp_y_room" ) { $work.MAP = "PvP : ヨーヨーモード控え室" }
   elseif( $work.MAP -eq "ein_fild01" ) { $work.MAP = "アインブロックフィールド 01" }
   elseif( $work.MAP -eq "ein_fild02" ) { $work.MAP = "アインブロックフィールド 02" }
   elseif( $work.MAP -eq "ein_fild03" ) { $work.MAP = "アインブロックフィールド 03" }
   elseif( $work.MAP -eq "ein_fild04" ) { $work.MAP = "アインブロックフィールド 04" }
   elseif( $work.MAP -eq "ein_fild05" ) { $work.MAP = "アインブロックフィールド 05" }
   elseif( $work.MAP -eq "ein_fild06" ) { $work.MAP = "アインブロックフィールド 06" }
   elseif( $work.MAP -eq "ein_fild07" ) { $work.MAP = "アインブロックフィールド 07" }
   elseif( $work.MAP -eq "ein_fild08" ) { $work.MAP = "アインブロックフィールド 08" }
   elseif( $work.MAP -eq "ein_fild09" ) { $work.MAP = "アインブロックフィールド 09" }
   elseif( $work.MAP -eq "ein_fild10" ) { $work.MAP = "アインブロックフィールド 10" }
   elseif( $work.MAP -eq "gl_chyard_" ) { $work.MAP = "悪夢のグラストヘイムカタコンベ" }
   elseif( $work.MAP -eq "gl_cas02_" ) { $work.MAP = "悪夢のグラストヘイム古城2F" }
   elseif( $work.MAP -eq "1@jtb" ) { $work.MAP = "悪夢のジターバグ" }
   elseif( $work.MAP -eq "abyss_01" ) { $work.MAP = "アビスレイク地下洞窟 01" }
   elseif( $work.MAP -eq "abyss_02" ) { $work.MAP = "アビスレイク地下洞窟 02" }
   elseif( $work.MAP -eq "abyss_03" ) { $work.MAP = "アビスレイク地下洞窟 03" }
   elseif( $work.MAP -eq "ama_dun01" ) { $work.MAP = "アマツダンジョン 01（畳の迷宮）" }
   elseif( $work.MAP -eq "ama_dun02" ) { $work.MAP = "アマツダンジョン 02（地下戦場跡）" }
   elseif( $work.MAP -eq "ama_dun03" ) { $work.MAP = "アマツダンジョン 03（アマツ地下神社）" }
   elseif( $work.MAP -eq "ama_fild01" ) { $work.MAP = "アマツフィールド 01" }
   elseif( $work.MAP -eq "ayothaya" ) { $work.MAP = "アユタヤ" }
   elseif( $work.MAP -eq "ayo_dun01" ) { $work.MAP = "アユタヤダンジョン 01（古代遺跡迷宮）" }
   elseif( $work.MAP -eq "ayo_dun02" ) { $work.MAP = "アユタヤダンジョン 02（古代遺跡内部）" }
   elseif( $work.MAP -eq "ayo_fild01" ) { $work.MAP = "アユタヤフィールド 01" }
   elseif( $work.MAP -eq "ayo_fild02" ) { $work.MAP = "アユタヤフィールド 02" }
   elseif( $work.MAP -eq "anthell01" ) { $work.MAP = "蟻地獄ダンジョン B1F" }
   elseif( $work.MAP -eq "anthell02" ) { $work.MAP = "蟻地獄ダンジョン B2F" }
   elseif( $work.MAP -eq "arena_room" ) { $work.MAP = "アリーナ待機室" }
   elseif( $work.MAP -eq "alde_gld" ) { $work.MAP = "アルデバラン衛星都市ルイーナ" }
   elseif( $work.MAP -eq "alde_dun01" ) { $work.MAP = "アルデバラン時計塔地下 1F" }
   elseif( $work.MAP -eq "alde_dun02" ) { $work.MAP = "アルデバラン時計塔地下 2F" }
   elseif( $work.MAP -eq "alde_dun03" ) { $work.MAP = "アルデバラン時計塔地下 3F" }
   elseif( $work.MAP -eq "alde_dun04" ) { $work.MAP = "アルデバラン時計塔地下 4F" }
   elseif( $work.MAP -eq "c_tower1" ) { $work.MAP = "アルデバラン時計塔地上 1F" }
   elseif( $work.MAP -eq "c_tower2" ) { $work.MAP = "アルデバラン時計塔地上 2F" }
   elseif( $work.MAP -eq "c_tower3" ) { $work.MAP = "アルデバラン時計塔地上 3F" }
   elseif( $work.MAP -eq "c_tower4" ) { $work.MAP = "アルデバラン時計塔地上 4F" }
   elseif( $work.MAP -eq "rachel" ) { $work.MAP = "アルナベルツ教国首都 ラヘル" }
   elseif( $work.MAP -eq "nyd_dun01" ) { $work.MAP = "イグドラシル中心部 01" }
   elseif( $work.MAP -eq "nyd_dun02" ) { $work.MAP = "イグドラシル中心部 02" }
   elseif( $work.MAP -eq "dew_dun02" ) { $work.MAP = "イスタナ洞窟" }
   elseif( $work.MAP -eq "iz_dun04" ) { $work.MAP = "イズルード海底神殿" }
   elseif( $work.MAP -eq "iz_dun00" ) { $work.MAP = "イズルード海底洞窟 1層" }
   elseif( $work.MAP -eq "iz_dun01" ) { $work.MAP = "イズルード海底洞窟 2層" }
   elseif( $work.MAP -eq "iz_dun02" ) { $work.MAP = "イズルード海底洞窟 3層" }
   elseif( $work.MAP -eq "iz_dun03" ) { $work.MAP = "イズルード海底洞窟 4層" }
   elseif( $work.MAP -eq "iz_dun05" ) { $work.MAP = "イズルード海底都市" }
   elseif( $work.MAP -eq "1@gl_k" ) { $work.MAP = "古の騎士団01" }
   elseif( $work.MAP -eq "2@gl_k" ) { $work.MAP = "古の騎士団02" }
   elseif( $work.MAP -eq "prt_gld" ) { $work.MAP = "ヴァルキリーレルム" }
   elseif( $work.MAP -eq "aru_gld" ) { $work.MAP = "ヴァルフレイヤ" }
   elseif( $work.MAP -eq "ver_tunn" ) { $work.MAP = "ウェルス外郭トンネル" }
   elseif( $work.MAP -eq "verus03" ) { $work.MAP = "ウェルス中央広場" }
   elseif( $work.MAP -eq "verus04" ) { $work.MAP = "ウェルス発掘地" }
   elseif( $work.MAP -eq "slabw01_jp" ) { $work.MAP = "ヴェルナー研究所 C棟" }
   elseif( $work.MAP -eq "1@pac" ) { $work.MAP = "恨みの淵(回廊)" }
   elseif( $work.MAP -eq "um_dun01" ) { $work.MAP = "ウンバラダンジョン 01（大樹の道）" }
   elseif( $work.MAP -eq "um_dun02" ) { $work.MAP = "ウンバラダンジョン 02（深奥の密林）" }
   elseif( $work.MAP -eq "um_fild01" ) { $work.MAP = "ウンバラフィールド 01（ルルカ森）" }
   elseif( $work.MAP -eq "um_fild02" ) { $work.MAP = "ウンバラフィールド 02（フムガ森）" }
   elseif( $work.MAP -eq "um_fild03" ) { $work.MAP = "ウンバラフィールド 03（カララ沼）" }
   elseif( $work.MAP -eq "um_fild04" ) { $work.MAP = "ウンバラフィールド 04（フムガジャングル）" }
   elseif( $work.MAP -eq "umbala" ) { $work.MAP = "ウータン族の村ウンバラ" }
   elseif( $work.MAP -eq "que_avan01" ) { $work.MAP = "エイヴァント研究室" }
   elseif( $work.MAP -eq "1@w_o_c" ) { $work.MAP = "永劫の戦" }
   elseif( $work.MAP -eq "2@w_o_c" ) { $work.MAP = "永劫の戦" }
   elseif( $work.MAP -eq "3@w_o_c" ) { $work.MAP = "永劫の戦" }
   elseif( $work.MAP -eq "izlude" ) { $work.MAP = "衛星都市イズルード" }
   elseif( $work.MAP -eq "1@ecl" ) { $work.MAP = "エクラージュ 内部" }
   elseif( $work.MAP -eq "mbt_a" ) { $work.MAP = "エリアA 集合地点" }
   elseif( $work.MAP -eq "mbt_d" ) { $work.MAP = "エリアD 集合地点" }
   elseif( $work.MAP -eq "mbt_i" ) { $work.MAP = "エリアI 集合地点" }
   elseif( $work.MAP -eq "1@tower" ) { $work.MAP = "エンドレスタワー 1層（1?25F）" }
   elseif( $work.MAP -eq "2@tower" ) { $work.MAP = "エンドレスタワー 2層（26?50F）" }
   elseif( $work.MAP -eq "3@tower" ) { $work.MAP = "エンドレスタワー 3層（51?75F）" }
   elseif( $work.MAP -eq "4@tower" ) { $work.MAP = "エンドレスタワー 4層（76?99F）" }
   elseif( $work.MAP -eq "5@tower" ) { $work.MAP = "エンドレスタワー 5層（100F）" }
   elseif( $work.MAP -eq "6@tower" ) { $work.MAP = "エンドレスタワー 覇王の間" }
   elseif( $work.MAP -eq "mosk_dun03" ) { $work.MAP = "奥深い森" }
   elseif( $work.MAP -eq "tra_hall" ) { $work.MAP = "お試し道場" }
   elseif( $work.MAP -eq "xmas_dun01" ) { $work.MAP = "おもちゃ工場ダンジョン 01（倉庫）" }
   elseif( $work.MAP -eq "xmas_dun02" ) { $work.MAP = "おもちゃ工場ダンジョン 02（分類所）" }
   elseif( $work.MAP -eq "orcsdun01" ) { $work.MAP = "オーク地下洞窟 01" }
   elseif( $work.MAP -eq "1@orcs" ) { $work.MAP = "オーク地下洞窟 01（過去）" }
   elseif( $work.MAP -eq "orcsdun02" ) { $work.MAP = "オーク地下洞窟 02" }
   elseif( $work.MAP -eq "2@orcs" ) { $work.MAP = "オーク地下洞窟 02（過去）" }
   elseif( $work.MAP -eq "odin_tem01" ) { $work.MAP = "オーディン神殿 01" }
   elseif( $work.MAP -eq "odin_tem02" ) { $work.MAP = "オーディン神殿 02" }
   elseif( $work.MAP -eq "odin_tem03" ) { $work.MAP = "オーディン神殿 03" }
   elseif( $work.MAP -eq "gon_test" ) { $work.MAP = "格闘場" }
   elseif( $work.MAP -eq "1@glast" ) { $work.MAP = "過去のグラストヘイム" }
   elseif( $work.MAP -eq "te_alde_gld" ) { $work.MAP = "カプラガーデン" }
   elseif( $work.MAP -eq "dic_fild01" ) { $work.MAP = "カミダル山麓 01" }
   elseif( $work.MAP -eq "dic_fild02" ) { $work.MAP = "カミダル山麓 02" }
   elseif( $work.MAP -eq "dic_dun01" ) { $work.MAP = "カミダルトンネル" }
   elseif( $work.MAP -eq "kh_kiehl01" ) { $work.MAP = "キエルの部屋 01" }
   elseif( $work.MAP -eq "kh_kiehl02" ) { $work.MAP = "キエルの部屋 02" }
   elseif( $work.MAP -eq "kh_dun01" ) { $work.MAP = "機械人形工場 B1F" }
   elseif( $work.MAP -eq "kh_dun02" ) { $work.MAP = "機械人形工場 B2F" }
   elseif( $work.MAP -eq "lighthalzen" ) { $work.MAP = "企業都市リヒタルゼン" }
   elseif( $work.MAP -eq "payon_p" ) { $work.MAP = "旧フェイヨン" }
   elseif( $work.MAP -eq "veins" ) { $work.MAP = "峡谷都市ベインス" }
   elseif( $work.MAP -eq "que_qaru01" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "que_qaru02" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "que_qaru03" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "que_qaru04" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "que_qaru05" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "que_qsch01" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "que_qsch02" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "que_qsch03" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "que_qsch04" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "que_qsch05" ) { $work.MAP = "虚像のオーコルニル" }
   elseif( $work.MAP -eq "1@mist" ) { $work.MAP = "霧の森" }
   elseif( $work.MAP -eq "gld_dun02" ) { $work.MAP = "ギルドダンジョン アルデバラン" }
   elseif( $work.MAP -eq "arug_dun01" ) { $work.MAP = "ギルドダンジョン アルナベルツ" }
   elseif( $work.MAP -eq "teg_dun02" ) { $work.MAP = "ギルドダンジョン カプラガーデン" }
   elseif( $work.MAP -eq "teg_dun01" ) { $work.MAP = "ギルドダンジョン グロリア" }
   elseif( $work.MAP -eq "gld_dun04" ) { $work.MAP = "ギルドダンジョン ゲフェン" }
   elseif( $work.MAP -eq "schg_dun01" ) { $work.MAP = "ギルドダンジョン シュバルツバルド" }
   elseif( $work.MAP -eq "gld_dun01" ) { $work.MAP = "ギルドダンジョン フェイヨン" }
   elseif( $work.MAP -eq "gld_dun03" ) { $work.MAP = "ギルドダンジョン プロンテラ" }
   elseif( $work.MAP -eq "rockrdg1" ) { $work.MAP = "キワワ砂漠 01" }
   elseif( $work.MAP -eq "rockrdg2" ) { $work.MAP = "キワワ砂漠 02" }
   elseif( $work.MAP -eq "1@lhz" ) { $work.MAP = "禁忌の研究所" }
   elseif( $work.MAP -eq "mosk_fild01" ) { $work.MAP = "クジラ島" }
   elseif( $work.MAP -eq "dew_dun01" ) { $work.MAP = "クラカト火山" }
   elseif( $work.MAP -eq "gl_step" ) { $work.MAP = "グラストヘイム 階段ダンジョン" }
   elseif( $work.MAP -eq "gl_chyard" ) { $work.MAP = "グラストヘイム カタコンベ" }
   elseif( $work.MAP -eq "gl_knt01" ) { $work.MAP = "グラストヘイム 騎士団内01" }
   elseif( $work.MAP -eq "gl_knt02" ) { $work.MAP = "グラストヘイム 騎士団内02" }
   elseif( $work.MAP -eq "glast_01" ) { $work.MAP = "グラストヘイム 古城" }
   elseif( $work.MAP -eq "glast_01" ) { $work.MAP = "グラストヘイム 古城" }
   elseif( $work.MAP -eq "gl_cas01" ) { $work.MAP = "グラストヘイム 古城1F" }
   elseif( $work.MAP -eq "gl_cas02" ) { $work.MAP = "グラストヘイム 古城2F" }
   elseif( $work.MAP -eq "gl_in01" ) { $work.MAP = "グラストヘイム 室内01" }
   elseif( $work.MAP -eq "gl_church" ) { $work.MAP = "グラストヘイム 修道院" }
   elseif( $work.MAP -eq "gl_prison" ) { $work.MAP = "グラストヘイム 地下監獄00" }
   elseif( $work.MAP -eq "gl_prison1" ) { $work.MAP = "グラストヘイム 地下監獄01" }
   elseif( $work.MAP -eq "gl_dun01" ) { $work.MAP = "グラストヘイム 最下層地下洞窟01" }
   elseif( $work.MAP -eq "gl_dun02" ) { $work.MAP = "グラストヘイム 最下層地下洞窟02" }
   elseif( $work.MAP -eq "gl_sew01" ) { $work.MAP = "グラストヘイム地下水路 01" }
   elseif( $work.MAP -eq "gl_sew02" ) { $work.MAP = "グラストヘイム地下水路 02" }
   elseif( $work.MAP -eq "gl_sew03" ) { $work.MAP = "グラストヘイム地下水路 03" }
   elseif( $work.MAP -eq "gl_sew04" ) { $work.MAP = "グラストヘイム地下水路 04" }
   elseif( $work.MAP -eq "te_prt_gld" ) { $work.MAP = "グロリア" }
   elseif( $work.MAP -eq "gefenia01" ) { $work.MAP = "ゲフェニア 01" }
   elseif( $work.MAP -eq "gefenia02" ) { $work.MAP = "ゲフェニア 02" }
   elseif( $work.MAP -eq "gefenia03" ) { $work.MAP = "ゲフェニア 03" }
   elseif( $work.MAP -eq "gefenia04" ) { $work.MAP = "ゲフェニア 04" }
   elseif( $work.MAP -eq "gef_dun00" ) { $work.MAP = "ゲフェン地下ダンジョン B1F" }
   elseif( $work.MAP -eq "gef_dun01" ) { $work.MAP = "ゲフェン地下ダンジョン B2F" }
   elseif( $work.MAP -eq "gef_dun02" ) { $work.MAP = "ゲフェン地下ダンジョン B3F" }
   elseif( $work.MAP -eq "gef_dun03" ) { $work.MAP = "ゲフェン地下ダンジョン B4F" }
   elseif( $work.MAP -eq "gef_fild00" ) { $work.MAP = "ゲフェンフィールド 00" }
   elseif( $work.MAP -eq "gef_fild01" ) { $work.MAP = "ゲフェンフィールド 01" }
   elseif( $work.MAP -eq "gef_fild02" ) { $work.MAP = "ゲフェンフィールド 02" }
   elseif( $work.MAP -eq "gef_fild03" ) { $work.MAP = "ゲフェンフィールド 03" }
   elseif( $work.MAP -eq "gef_fild04" ) { $work.MAP = "ゲフェンフィールド 04" }
   elseif( $work.MAP -eq "gef_fild05" ) { $work.MAP = "ゲフェンフィールド 05" }
   elseif( $work.MAP -eq "gef_fild06" ) { $work.MAP = "ゲフェンフィールド 06" }
   elseif( $work.MAP -eq "gef_fild07" ) { $work.MAP = "ゲフェンフィールド 07" }
   elseif( $work.MAP -eq "gef_fild08" ) { $work.MAP = "ゲフェンフィールド 08" }
   elseif( $work.MAP -eq "gef_fild09" ) { $work.MAP = "ゲフェンフィールド 09" }
   elseif( $work.MAP -eq "gef_fild10" ) { $work.MAP = "ゲフェンフィールド 10" }
   elseif( $work.MAP -eq "gef_fild11" ) { $work.MAP = "ゲフェンフィールド 11" }
   elseif( $work.MAP -eq "gef_fild12" ) { $work.MAP = "ゲフェンフィールド 12（コードの森）" }
   elseif( $work.MAP -eq "gef_fild13" ) { $work.MAP = "ゲフェンフィールド 13（ブリトニア）" }
   elseif( $work.MAP -eq "gef_fild14" ) { $work.MAP = "ゲフェンフィールド 14（オーク西の村）" }
   elseif( $work.MAP -eq "1@gef" ) { $work.MAP = "ゲフェン魔法大会" }
   elseif( $work.MAP -eq "1@ge_st" ) { $work.MAP = "ゲフェン魔法大会" }
   elseif( $work.MAP -eq "verus02" ) { $work.MAP = "研究棟-WISH" }
   elseif( $work.MAP -eq "comodo" ) { $work.MAP = "幻想の島コモド" }
   elseif( $work.MAP -eq "ein_dun01" ) { $work.MAP = "鉱山ダンジョン 01" }
   elseif( $work.MAP -eq "ein_dun02" ) { $work.MAP = "鉱山ダンジョン 02" }
   elseif( $work.MAP -eq "manuk" ) { $work.MAP = "鉱山の街 マヌク" }
   elseif( $work.MAP -eq "einbroch" ) { $work.MAP = "鋼鉄の都市アインブロック" }
   elseif( $work.MAP -eq "ice_dun01" ) { $work.MAP = "氷の洞窟 01" }
   elseif( $work.MAP -eq "ice_dun02" ) { $work.MAP = "氷の洞窟 02" }
   elseif( $work.MAP -eq "ice_dun03" ) { $work.MAP = "氷の洞窟 03" }
   elseif( $work.MAP -eq "aldebaran" ) { $work.MAP = "国境都市アルデバラン" }
   elseif( $work.MAP -eq "louyang" ) { $work.MAP = "古都 龍之城" }
   elseif( $work.MAP -eq "beach_dun" ) { $work.MAP = "コモドダンジョン 01（西洞窟カル）" }
   elseif( $work.MAP -eq "beach_dun2" ) { $work.MAP = "コモドダンジョン 02（北洞窟ルワンダ）" }
   elseif( $work.MAP -eq "beach_dun3" ) { $work.MAP = "コモドダンジョン 03（東洞窟マオ）" }
   elseif( $work.MAP -eq "cmd_fild01" ) { $work.MAP = "コモドフィールド 01（パプチカ森）" }
   elseif( $work.MAP -eq "cmd_fild02" ) { $work.MAP = "コモドフィールド 02（ココモビーチ）" }
   elseif( $work.MAP -eq "cmd_fild03" ) { $work.MAP = "コモドフィールド 03（ジナイ沼）" }
   elseif( $work.MAP -eq "cmd_fild04" ) { $work.MAP = "コモドフィールド 04（ココモビーチ）" }
   elseif( $work.MAP -eq "cmd_fild05" ) { $work.MAP = "コモドフィールド 05（パプチカ森境）" }
   elseif( $work.MAP -eq "cmd_fild06" ) { $work.MAP = "コモドフィールド 06（サンダルマン要塞西）" }
   elseif( $work.MAP -eq "cmd_fild07" ) { $work.MAP = "コモドフィールド 07（ファロス燈台島）" }
   elseif( $work.MAP -eq "cmd_fild08" ) { $work.MAP = "コモドフィールド 08（サンダルマン要塞東）" }
   elseif( $work.MAP -eq "cmd_fild09" ) { $work.MAP = "コモドフィールド 09（サンダルマン要塞南）" }
   elseif( $work.MAP -eq "gon_dun01" ) { $work.MAP = "コンロンダンジョン 01（西王母神殿）" }
   elseif( $work.MAP -eq "gon_dun02" ) { $work.MAP = "コンロンダンジョン 02（神仙の碁盤）" }
   elseif( $work.MAP -eq "gon_dun03" ) { $work.MAP = "コンロンダンジョン 03（武陵桃源）" }
   elseif( $work.MAP -eq "gon_fild01" ) { $work.MAP = "コンロンフィールド 01" }
   elseif( $work.MAP -eq "einbech" ) { $work.MAP = "採鉱の村アインベフ" }
   elseif( $work.MAP -eq "1@uns" ) { $work.MAP = "最後の部屋" }
   elseif( $work.MAP -eq "morocc" ) { $work.MAP = "砂漠の都市モロク" }
   elseif( $work.MAP -eq "dicastes01" ) { $work.MAP = "サファ族の首都 エルディカスティス" }
   elseif( $work.MAP -eq "jp_ev_pro" ) { $work.MAP = "サモンパーク" }
   elseif( $work.MAP -eq "jp_ev_mor" ) { $work.MAP = "サモンパーク" }
   elseif( $work.MAP -eq "jp_ev_pay" ) { $work.MAP = "サモンパーク" }
   elseif( $work.MAP -eq "jp_ev_gef" ) { $work.MAP = "サモンパーク" }
   elseif( $work.MAP -eq "jp_ev_alb" ) { $work.MAP = "サモンパーク" }
   elseif( $work.MAP -eq "jp_ev_yun" ) { $work.MAP = "サモンパーク" }
   elseif( $work.MAP -eq "1@sara" ) { $work.MAP = "サラの記憶" }
   elseif( $work.MAP -eq "payon" ) { $work.MAP = "山岳の都市フェイヨン" }
   elseif( $work.MAP -eq "moc_fild22b" ) { $work.MAP = "時空の裂け目" }
   elseif( $work.MAP -eq "moc_fild20" ) { $work.MAP = "次元の狭間 01" }
   elseif( $work.MAP -eq "moc_fild21" ) { $work.MAP = "次元の狭間 02" }
   elseif( $work.MAP -eq "moc_fild22" ) { $work.MAP = "次元の狭間 03" }
   elseif( $work.MAP -eq "dali" ) { $work.MAP = "次元の狭間 時の通路01" }
   elseif( $work.MAP -eq "dali02" ) { $work.MAP = "次元の狭間 時の通路02" }
   elseif( $work.MAP -eq "niflheim" ) { $work.MAP = "死者の街ニブルヘイム" }
   elseif( $work.MAP -eq "verus01" ) { $work.MAP = "実験棟-OPTATIO" }
   elseif( $work.MAP -eq "ac_prac_01" ) { $work.MAP = "実習室（海岸）" }
   elseif( $work.MAP -eq "ac_prac_03" ) { $work.MAP = "実習室（高原）" }
   elseif( $work.MAP -eq "ac_prac_05" ) { $work.MAP = "実習室（砂漠）" }
   elseif( $work.MAP -eq "ac_prac_02" ) { $work.MAP = "実習室（島）" }
   elseif( $work.MAP -eq "ac_prac_04" ) { $work.MAP = "実習室（炭鉱）" }
   elseif( $work.MAP -eq "abbey01" ) { $work.MAP = "修道院 01" }
   elseif( $work.MAP -eq "abbey02" ) { $work.MAP = "修道院 02" }
   elseif( $work.MAP -eq "abbey03" ) { $work.MAP = "修道院 03" }
   elseif( $work.MAP -eq "yuno_fild01" ) { $work.MAP = "ジュノーフィールド 01（国境検問所）" }
   elseif( $work.MAP -eq "yuno_fild02" ) { $work.MAP = "ジュノーフィールド 02（キル・ハイルの別荘）" }
   elseif( $work.MAP -eq "yuno_fild03" ) { $work.MAP = "ジュノーフィールド 03（エルメスプレート）" }
   elseif( $work.MAP -eq "yuno_fild04" ) { $work.MAP = "ジュノーフィールド 04（エルメスプレート）" }
   elseif( $work.MAP -eq "yuno_fild05" ) { $work.MAP = "ジュノーフィールド 05（エルメスプレート）" }
   elseif( $work.MAP -eq "yuno_fild06" ) { $work.MAP = "ジュノーフィールド 06（エルメスプレート）" }
   elseif( $work.MAP -eq "yuno_fild07" ) { $work.MAP = "ジュノーフィールド 07（エルメス峡谷）" }
   elseif( $work.MAP -eq "yuno_fild08" ) { $work.MAP = "ジュノーフィールド 08（キル・ハイル学院）" }
   elseif( $work.MAP -eq "yuno_fild09" ) { $work.MAP = "ジュノーフィールド 09（シュバルツバルド警備隊野営地）" }
   elseif( $work.MAP -eq "yuno_fild10" ) { $work.MAP = "ジュノーフィールド 10" }
   elseif( $work.MAP -eq "yuno_fild11" ) { $work.MAP = "ジュノーフィールド 11" }
   elseif( $work.MAP -eq "yuno_fild12" ) { $work.MAP = "ジュノーフィールド 12（国境検問所）" }
   elseif( $work.MAP -eq "yuno" ) { $work.MAP = "シュバルツバルド共和国の首都ジュノー" }
   elseif( $work.MAP -eq "jupe_core" ) { $work.MAP = "ジュピロス中心部" }
   elseif( $work.MAP -eq "juperos_01" ) { $work.MAP = "ジュピロス廃墟 01" }
   elseif( $work.MAP -eq "juperos_02" ) { $work.MAP = "ジュピロス廃墟 02" }
   elseif( $work.MAP -eq "ver_eju" ) { $work.MAP = "ジュピロス東側" }
   elseif( $work.MAP -eq "gonryun" ) { $work.MAP = "神仙の島コンロン" }
   elseif( $work.MAP -eq "moc_prydb1" ) { $work.MAP = "シーフギルド" }
   elseif( $work.MAP -eq "dic_dun03" ) { $work.MAP = "スカラバガーデン" }
   elseif( $work.MAP -eq "dic_dun02" ) { $work.MAP = "スカラバホール" }
   elseif( $work.MAP -eq "in_sphinx1" ) { $work.MAP = "スフィンクスダンジョン B1F" }
   elseif( $work.MAP -eq "in_sphinx2" ) { $work.MAP = "スフィンクスダンジョン B2F" }
   elseif( $work.MAP -eq "in_sphinx3" ) { $work.MAP = "スフィンクスダンジョン B3F" }
   elseif( $work.MAP -eq "in_sphinx4" ) { $work.MAP = "スフィンクスダンジョン B4F" }
   elseif( $work.MAP -eq "in_sphinx5" ) { $work.MAP = "スフィンクスダンジョン B5F" }
   elseif( $work.MAP -eq "spl_fild01" ) { $work.MAP = "スプレンディッドフィールド 01" }
   elseif( $work.MAP -eq "spl_fild02" ) { $work.MAP = "スプレンディッドフィールド 02" }
   elseif( $work.MAP -eq "spl_fild03" ) { $work.MAP = "スプレンディッドフィールド 03" }
   elseif( $work.MAP -eq "prt_monk" ) { $work.MAP = "聖カピトーリナ修道院" }
   elseif( $work.MAP -eq "que_lhz" ) { $work.MAP = "生体工学研究所" }
   elseif( $work.MAP -eq "lhz_dun01" ) { $work.MAP = "生体工学研究所 01" }
   elseif( $work.MAP -eq "lhz_dun02" ) { $work.MAP = "生体工学研究所 02" }
   elseif( $work.MAP -eq "lhz_dun03" ) { $work.MAP = "生体工学研究所 03" }
   elseif( $work.MAP -eq "lhz_dun04" ) { $work.MAP = "生体工学研究所 04" }
   elseif( $work.MAP -eq "lhz_dun_n" ) { $work.MAP = "戦死者の墓" }
   elseif( $work.MAP -eq "splendide" ) { $work.MAP = "前線基地 スプレンディッド" }
   elseif( $work.MAP -eq "moc_fild01" ) { $work.MAP = "ソグラト砂漠 01" }
   elseif( $work.MAP -eq "moc_fild02" ) { $work.MAP = "ソグラト砂漠 02" }
   elseif( $work.MAP -eq "moc_fild03" ) { $work.MAP = "ソグラト砂漠 03" }
   elseif( $work.MAP -eq "moc_fild04" ) { $work.MAP = "ソグラト砂漠 04" }
   elseif( $work.MAP -eq "moc_fild05" ) { $work.MAP = "ソグラト砂漠 05" }
   elseif( $work.MAP -eq "moc_fild06" ) { $work.MAP = "ソグラト砂漠 06" }
   elseif( $work.MAP -eq "moc_fild07" ) { $work.MAP = "ソグラト砂漠 07" }
   elseif( $work.MAP -eq "moc_fild08" ) { $work.MAP = "ソグラト砂漠 08" }
   elseif( $work.MAP -eq "moc_fild09" ) { $work.MAP = "ソグラト砂漠 09" }
   elseif( $work.MAP -eq "moc_fild10" ) { $work.MAP = "ソグラト砂漠 10" }
   elseif( $work.MAP -eq "moc_fild11" ) { $work.MAP = "ソグラト砂漠 11" }
   elseif( $work.MAP -eq "moc_fild12" ) { $work.MAP = "ソグラト砂漠 12" }
   elseif( $work.MAP -eq "moc_fild13" ) { $work.MAP = "ソグラト砂漠 13" }
   elseif( $work.MAP -eq "moc_fild14" ) { $work.MAP = "ソグラト砂漠 14" }
   elseif( $work.MAP -eq "moc_fild15" ) { $work.MAP = "ソグラト砂漠 15" }
   elseif( $work.MAP -eq "moc_fild16" ) { $work.MAP = "ソグラト砂漠 16" }
   elseif( $work.MAP -eq "moc_fild17" ) { $work.MAP = "ソグラト砂漠 17" }
   elseif( $work.MAP -eq "moc_fild18" ) { $work.MAP = "ソグラト砂漠 18" }
   elseif( $work.MAP -eq "moc_fild19" ) { $work.MAP = "ソグラト砂漠 19" }
   elseif( $work.MAP -eq "monbt1_a1" ) { $work.MAP = "第1作戦エリア" }
   elseif( $work.MAP -eq "monbt1_d1" ) { $work.MAP = "第1作戦エリア" }
   elseif( $work.MAP -eq "monbt1_i1" ) { $work.MAP = "第1作戦エリア" }
   elseif( $work.MAP -eq "monbt1_a2" ) { $work.MAP = "第2作戦エリア" }
   elseif( $work.MAP -eq "monbt1_d2" ) { $work.MAP = "第2作戦エリア" }
   elseif( $work.MAP -eq "monbt1_i2" ) { $work.MAP = "第2作戦エリア" }
   elseif( $work.MAP -eq "monbt1_a3" ) { $work.MAP = "第3作戦エリア" }
   elseif( $work.MAP -eq "monbt1_d3" ) { $work.MAP = "第3作戦エリア" }
   elseif( $work.MAP -eq "monbt1_i3" ) { $work.MAP = "第3作戦エリア" }
   elseif( $work.MAP -eq "monbt1_a4" ) { $work.MAP = "第4作戦エリア" }
   elseif( $work.MAP -eq "monbt1_d4" ) { $work.MAP = "第4作戦エリア" }
   elseif( $work.MAP -eq "monbt1_i4" ) { $work.MAP = "第4作戦エリア" }
   elseif( $work.MAP -eq "monbt1_a5" ) { $work.MAP = "第5作戦エリア" }
   elseif( $work.MAP -eq "monbt1_d5" ) { $work.MAP = "第5作戦エリア" }
   elseif( $work.MAP -eq "monbt1_i5" ) { $work.MAP = "第5作戦エリア" }
   elseif( $work.MAP -eq "monbt1_a6" ) { $work.MAP = "第6作戦エリア" }
   elseif( $work.MAP -eq "monbt1_d6" ) { $work.MAP = "第6作戦エリア" }
   elseif( $work.MAP -eq "monbt1_i6" ) { $work.MAP = "第6作戦エリア" }
   elseif( $work.MAP -eq "monbt1_a7" ) { $work.MAP = "第7作戦エリア" }
   elseif( $work.MAP -eq "monbt1_d7" ) { $work.MAP = "第7作戦エリア" }
   elseif( $work.MAP -eq "monbt1_i7" ) { $work.MAP = "第7作戦エリア" }
   elseif( $work.MAP -eq "monbt1_a8" ) { $work.MAP = "第8作戦エリア" }
   elseif( $work.MAP -eq "monbt1_d8" ) { $work.MAP = "第8作戦エリア" }
   elseif( $work.MAP -eq "monbt1_i8" ) { $work.MAP = "第8作戦エリア" }
   elseif( $work.MAP -eq "monbt1_a9" ) { $work.MAP = "第9作戦エリア" }
   elseif( $work.MAP -eq "monbt1_d9" ) { $work.MAP = "第9作戦エリア" }
   elseif( $work.MAP -eq "monbt1_i9" ) { $work.MAP = "第9作戦エリア" }
   elseif( $work.MAP -eq "force_1-1" ) { $work.MAP = "タイムアタックモード 1-1" }
   elseif( $work.MAP -eq "force_2-1" ) { $work.MAP = "タイムアタックモード 2-1" }
   elseif( $work.MAP -eq "force_3-1" ) { $work.MAP = "タイムアタックモード 3-1" }
   elseif( $work.MAP -eq "force_4-1" ) { $work.MAP = "タイムアタックモード 4-1" }
   elseif( $work.MAP -eq "force_5-1" ) { $work.MAP = "タイムアタックモード 5-1" }
   elseif( $work.MAP -eq "bra_dun01" ) { $work.MAP = "滝の中の洞窟 01" }
   elseif( $work.MAP -eq "bra_dun02" ) { $work.MAP = "滝の中の洞窟 02" }
   elseif( $work.MAP -eq "tha_t01" ) { $work.MAP = "タナトスタワー下層部 01" }
   elseif( $work.MAP -eq "tha_t02" ) { $work.MAP = "タナトスタワー下層部 02" }
   elseif( $work.MAP -eq "tha_t03" ) { $work.MAP = "タナトスタワー下層部 03" }
   elseif( $work.MAP -eq "tha_t04" ) { $work.MAP = "タナトスタワー下層部 04" }
   elseif( $work.MAP -eq "thana_boss" ) { $work.MAP = "タナトスタワー最上部" }
   elseif( $work.MAP -eq "tha_t05" ) { $work.MAP = "タナトスタワー上層部 05" }
   elseif( $work.MAP -eq "tha_t06" ) { $work.MAP = "タナトスタワー上層部 06" }
   elseif( $work.MAP -eq "tha_t07" ) { $work.MAP = "タナトスタワー上層部 07" }
   elseif( $work.MAP -eq "tha_t08" ) { $work.MAP = "タナトスタワー上層部 08" }
   elseif( $work.MAP -eq "tha_t09" ) { $work.MAP = "タナトスタワー上層部 09" }
   elseif( $work.MAP -eq "tha_t10" ) { $work.MAP = "タナトスタワー上層部 10" }
   elseif( $work.MAP -eq "tha_t11" ) { $work.MAP = "タナトスタワー上層部 11" }
   elseif( $work.MAP -eq "tha_t12" ) { $work.MAP = "タナトスタワー上層部 12" }
   elseif( $work.MAP -eq "tur_dun01" ) { $work.MAP = "タートルアイランド" }
   elseif( $work.MAP -eq "tur_dun01" ) { $work.MAP = "タートルアイランド" }
   elseif( $work.MAP -eq "tur_dun02" ) { $work.MAP = "タートルアイランドダンジョン 01" }
   elseif( $work.MAP -eq "tur_dun03" ) { $work.MAP = "タートルアイランドダンジョン 02（陽居村）" }
   elseif( $work.MAP -eq "tur_dun04" ) { $work.MAP = "タートルアイランドダンジョン 03（久陽宮）" }
   elseif( $work.MAP -eq "turbo_n_1" ) { $work.MAP = "ターボトラック競技場" }
   elseif( $work.MAP -eq "turbo_room" ) { $work.MAP = "ターボトラック控え室" }
   elseif( $work.MAP -eq "un_bunker" ) { $work.MAP = "地下シェルター" }
   elseif( $work.MAP -eq "un_bk_q" ) { $work.MAP = "地下シェルター(メモリーレコード)" }
   elseif( $work.MAP -eq "1@pump" ) { $work.MAP = "地下排水路" }
   elseif( $work.MAP -eq "2@pump" ) { $work.MAP = "地下排水路 最奥部" }
   elseif( $work.MAP -eq "1@mcd" ) { $work.MAP = "チャールストン工場" }
   elseif( $work.MAP -eq "1@lab" ) { $work.MAP = "中央実験室" }
   elseif( $work.MAP -eq "pay_gld" ) { $work.MAP = "チュンリム湖" }
   elseif( $work.MAP -eq "treasure01" ) { $work.MAP = "沈没船 1層" }
   elseif( $work.MAP -eq "treasure02" ) { $work.MAP = "沈没船 2層" }
   elseif( $work.MAP -eq "alb2trea" ) { $work.MAP = "沈没船の付近の島" }
   elseif( $work.MAP -eq "dewata" ) { $work.MAP = "デワタ" }
   elseif( $work.MAP -eq "dew_fild01" ) { $work.MAP = "デワタフィールド 01" }
   elseif( $work.MAP -eq "hugel" ) { $work.MAP = "田園都市フィゲル" }
   elseif( $work.MAP -eq "t_crack" ) { $work.MAP = "時の狭間" }
   elseif( $work.MAP -eq "ac_spec_03" ) { $work.MAP = "特別室（地下道）" }
   elseif( $work.MAP -eq "ac_spec_02" ) { $work.MAP = "特別室（廃墟）" }
   elseif( $work.MAP -eq "ac_spec_01" ) { $work.MAP = "特別室（湖）" }
   elseif( $work.MAP -eq "jawaii" ) { $work.MAP = "常夏の島 ジャワイ" }
   elseif( $work.MAP -eq "monbt1_a0" ) { $work.MAP = "突入待機地点 エリアA1" }
   elseif( $work.MAP -eq "monbt1_d0" ) { $work.MAP = "突入待機地点 エリアD1" }
   elseif( $work.MAP -eq "monbt1_i0" ) { $work.MAP = "突入待機地点 エリアI1" }
   elseif( $work.MAP -eq "thor_v01" ) { $work.MAP = "トール火山ダンジョン 01" }
   elseif( $work.MAP -eq "thor_v02" ) { $work.MAP = "トール火山ダンジョン 02" }
   elseif( $work.MAP -eq "thor_v03" ) { $work.MAP = "トール火山ダンジョン 03" }
   elseif( $work.MAP -eq "mal_in02" ) { $work.MAP = "ナビ号 船内" }
   elseif( $work.MAP -eq "nameless_i" ) { $work.MAP = "名もなき島 朝" }
   elseif( $work.MAP -eq "nameless_n" ) { $work.MAP = "名もなき島 夜" }
   elseif( $work.MAP -eq "sch_gld" ) { $work.MAP = "ニダヴェリール" }
   elseif( $work.MAP -eq "nif_fild01" ) { $work.MAP = "ニブルヘイムフィールド 01（秘境の村）" }
   elseif( $work.MAP -eq "nif_fild02" ) { $work.MAP = "ニブルヘイムフィールド 02（ギョル渓谷）" }
   elseif( $work.MAP -eq "1@nyd" ) { $work.MAP = "ニーズヘッグの巣" }
   elseif( $work.MAP -eq "2@nyd" ) { $work.MAP = "ニーズヘッグの巣" }
   elseif( $work.MAP -eq "c_tower1_" ) { $work.MAP = "捻じれた時間の時計塔地上 1F" }
   elseif( $work.MAP -eq "c_tower2_" ) { $work.MAP = "捻じれた時間の時計塔地上 2F" }
   elseif( $work.MAP -eq "c_tower3_" ) { $work.MAP = "捻じれた時間の時計塔地上 3F" }
   elseif( $work.MAP -eq "c_tower4_" ) { $work.MAP = "捻じれた時間の時計塔地上 4F" }
   elseif( $work.MAP -eq "mag_dun01" ) { $work.MAP = "ノーグロード 1層" }
   elseif( $work.MAP -eq "mag_dun02" ) { $work.MAP = "ノーグロード 2層" }
   elseif( $work.MAP -eq "izlu2dun" ) { $work.MAP = "バイラン島" }
   elseif( $work.MAP -eq "ma_scene01" ) { $work.MAP = "バコナワ湖" }
   elseif( $work.MAP -eq "1@ma_b" ) { $work.MAP = "バコナワの棲み処" }
   elseif( $work.MAP -eq "ecl_fild01" ) { $work.MAP = "花が咲き始めた大地" }
   elseif( $work.MAP -eq "ma_fild02" ) { $work.MAP = "バリオ・フォレスト" }
   elseif( $work.MAP -eq "ma_fild01" ) { $work.MAP = "バリオ・マヒワガ" }
   elseif( $work.MAP -eq "1@dth1" ) { $work.MAP = "ビオスの島 01" }
   elseif( $work.MAP -eq "1@dth2" ) { $work.MAP = "ビオスの島 02" }
   elseif( $work.MAP -eq "1@dth3" ) { $work.MAP = "ビオスの島 03" }
   elseif( $work.MAP -eq "1@air1" ) { $work.MAP = "飛行船" }
   elseif( $work.MAP -eq "1@air2" ) { $work.MAP = "飛行船" }
   elseif( $work.MAP -eq "airplane_01" ) { $work.MAP = "飛行船（シュバルツバルド国外線）" }
   elseif( $work.MAP -eq "bif_fild01" ) { $work.MAP = "ビフロスト 南部" }
   elseif( $work.MAP -eq "bif_fild02" ) { $work.MAP = "ビフロスト 北部" }
   elseif( $work.MAP -eq "ecl_tdun01" ) { $work.MAP = "ビフロストタワー 1階" }
   elseif( $work.MAP -eq "ecl_tdun02" ) { $work.MAP = "ビフロストタワー 2階" }
   elseif( $work.MAP -eq "ecl_tdun03" ) { $work.MAP = "ビフロストタワー 3階" }
   elseif( $work.MAP -eq "ma_dun01" ) { $work.MAP = "ビョンウンゴ病院1階" }
   elseif( $work.MAP -eq "ma_dun01_jp" ) { $work.MAP = "ビョンウンゴ病院2階" }
   elseif( $work.MAP -eq "moc_pryd01" ) { $work.MAP = "ピラミッドダンジョン 1F" }
   elseif( $work.MAP -eq "moc_pryd02" ) { $work.MAP = "ピラミッドダンジョン 2F" }
   elseif( $work.MAP -eq "moc_pryd03" ) { $work.MAP = "ピラミッドダンジョン 3F" }
   elseif( $work.MAP -eq "moc_pryd04" ) { $work.MAP = "ピラミッドダンジョン 4F" }
   elseif( $work.MAP -eq "moc_pryd05" ) { $work.MAP = "ピラミッドダンジョン B2F" }
   elseif( $work.MAP -eq "moc_pryd06" ) { $work.MAP = "ピラミッドダンジョン B3F" }
   elseif( $work.MAP -eq "moc_prydn1" ) { $work.MAP = "ピラミッドダンジョン 秘密の地下室01" }
   elseif( $work.MAP -eq "moc_prydn2" ) { $work.MAP = "ピラミッドダンジョン 秘密の地下室02" }
   elseif( $work.MAP -eq "que_dan01" ) { $work.MAP = "フィゲルフィールド" }
   elseif( $work.MAP -eq "hu_fild01" ) { $work.MAP = "フィゲルフィールド 01（タナトスタワー）" }
   elseif( $work.MAP -eq "hu_fild02" ) { $work.MAP = "フィゲルフィールド 02" }
   elseif( $work.MAP -eq "hu_fild03" ) { $work.MAP = "フィゲルフィールド 03" }
   elseif( $work.MAP -eq "hu_fild04" ) { $work.MAP = "フィゲルフィールド 04" }
   elseif( $work.MAP -eq "hu_fild05" ) { $work.MAP = "フィゲルフィールド 05（アビスレイク）" }
   elseif( $work.MAP -eq "hu_fild06" ) { $work.MAP = "フィゲルフィールド 06" }
   elseif( $work.MAP -eq "hu_fild07" ) { $work.MAP = "フィゲルフィールド 07" }
   elseif( $work.MAP -eq "2@cata" ) { $work.MAP = "封印された神殿（大封印祭壇）" }
   elseif( $work.MAP -eq "1@cata" ) { $work.MAP = "封印された神殿（墓地）" }
   elseif( $work.MAP -eq "1@face" ) { $work.MAP = "フェイスワームの巣" }
   elseif( $work.MAP -eq "pay_dun00" ) { $work.MAP = "フェイヨン地下洞窟 B1F" }
   elseif( $work.MAP -eq "pay_dun01" ) { $work.MAP = "フェイヨン地下洞窟 B2F" }
   elseif( $work.MAP -eq "pay_dun02" ) { $work.MAP = "フェイヨン地下洞窟 B3F" }
   elseif( $work.MAP -eq "pay_dun03" ) { $work.MAP = "フェイヨン地下洞窟 B4F（地下寺院）" }
   elseif( $work.MAP -eq "pay_dun04" ) { $work.MAP = "フェイヨン地下洞窟 B5F（地下寺院）" }
   elseif( $work.MAP -eq "pay_fild01" ) { $work.MAP = "フェイヨン迷いの森 01" }
   elseif( $work.MAP -eq "pay_fild02" ) { $work.MAP = "フェイヨン迷いの森 02" }
   elseif( $work.MAP -eq "pay_fild03" ) { $work.MAP = "フェイヨン迷いの森 03" }
   elseif( $work.MAP -eq "pay_fild04" ) { $work.MAP = "フェイヨン迷いの森 04" }
   elseif( $work.MAP -eq "pay_fild05" ) { $work.MAP = "フェイヨン迷いの森 05" }
   elseif( $work.MAP -eq "pay_fild06" ) { $work.MAP = "フェイヨン迷いの森 06" }
   elseif( $work.MAP -eq "pay_fild07" ) { $work.MAP = "フェイヨン迷いの森 07" }
   elseif( $work.MAP -eq "pay_fild08" ) { $work.MAP = "フェイヨン迷いの森 08" }
   elseif( $work.MAP -eq "pay_fild09" ) { $work.MAP = "フェイヨン迷いの森 09" }
   elseif( $work.MAP -eq "pay_fild10" ) { $work.MAP = "フェイヨン迷いの森 10" }
   elseif( $work.MAP -eq "pay_fild11" ) { $work.MAP = "フェイヨン迷いの森 11" }
   elseif( $work.MAP -eq "pay_arche" ) { $work.MAP = "フェイヨン弓手村" }
   elseif( $work.MAP -eq "mosk_dun02" ) { $work.MAP = "深い森" }
   elseif( $work.MAP -eq "mosk_ship" ) { $work.MAP = "船" }
   elseif( $work.MAP -eq "yggdrasil01" ) { $work.MAP = "フベルゲルミルの泉(イグドラシルの幹)" }
   elseif( $work.MAP -eq "brasilis" ) { $work.MAP = "ブラジリス" }
   elseif( $work.MAP -eq "bra_fild01" ) { $work.MAP = "ブラジリスフィールド 01" }
   elseif( $work.MAP -eq "dicastes02" ) { $work.MAP = "ブルーメヴァルト" }
   elseif( $work.MAP -eq "moro_vol" ) { $work.MAP = "フレイムヴァレー" }
   elseif( $work.MAP -eq "ra_san01" ) { $work.MAP = "フレイヤ大神殿聖域 01" }
   elseif( $work.MAP -eq "ra_san02" ) { $work.MAP = "フレイヤ大神殿聖域 02" }
   elseif( $work.MAP -eq "ra_san03" ) { $work.MAP = "フレイヤ大神殿聖域 03" }
   elseif( $work.MAP -eq "ra_san04" ) { $work.MAP = "フレイヤ大神殿聖域 04" }
   elseif( $work.MAP -eq "ra_san05" ) { $work.MAP = "フレイヤ大神殿聖域 05" }
   elseif( $work.MAP -eq "ra_temple" ) { $work.MAP = "フレイヤ大神殿（セスルムニル）" }
   elseif( $work.MAP -eq "pab_camp" ) { $work.MAP = "プロンテラ深淵" }
   elseif( $work.MAP -eq "pab_dun03" ) { $work.MAP = "プロンテラ深淵（回廊）" }
   elseif( $work.MAP -eq "pab_dun04" ) { $work.MAP = "プロンテラ深淵（旧市街地）" }
   elseif( $work.MAP -eq "pab_dun02" ) { $work.MAP = "プロンテラ深淵（祭祀場）" }
   elseif( $work.MAP -eq "pab_dun01" ) { $work.MAP = "プロンテラ深淵（庭園）" }
   elseif( $work.MAP -eq "prt_sewb1" ) { $work.MAP = "プロンテラ地下水路 B1F" }
   elseif( $work.MAP -eq "prt_sewb2" ) { $work.MAP = "プロンテラ地下水路 B2F" }
   elseif( $work.MAP -eq "prt_sewb3" ) { $work.MAP = "プロンテラ地下水路 B3F" }
   elseif( $work.MAP -eq "prt_sewb4" ) { $work.MAP = "プロンテラ地下水路 B4F" }
   elseif( $work.MAP -eq "prt_fild00" ) { $work.MAP = "プロンテラフィールド 00" }
   elseif( $work.MAP -eq "prt_fild01" ) { $work.MAP = "プロンテラフィールド 01" }
   elseif( $work.MAP -eq "prt_fild02" ) { $work.MAP = "プロンテラフィールド 02" }
   elseif( $work.MAP -eq "prt_fild03" ) { $work.MAP = "プロンテラフィールド 03" }
   elseif( $work.MAP -eq "prt_fild04" ) { $work.MAP = "プロンテラフィールド 04" }
   elseif( $work.MAP -eq "prt_fild05" ) { $work.MAP = "プロンテラフィールド 05" }
   elseif( $work.MAP -eq "prt_fild06" ) { $work.MAP = "プロンテラフィールド 06" }
   elseif( $work.MAP -eq "prt_fild07" ) { $work.MAP = "プロンテラフィールド 07" }
   elseif( $work.MAP -eq "prt_fild08" ) { $work.MAP = "プロンテラフィールド 08" }
   elseif( $work.MAP -eq "prt_fild09" ) { $work.MAP = "プロンテラフィールド 09" }
   elseif( $work.MAP -eq "prt_fild10" ) { $work.MAP = "プロンテラフィールド 10" }
   elseif( $work.MAP -eq "prt_fild11" ) { $work.MAP = "プロンテラフィールド 11" }
   elseif( $work.MAP -eq "1@ma_c" ) { $work.MAP = "ブワヤの巣" }
   elseif( $work.MAP -eq "ma_c_jp" ) { $work.MAP = "ブワヤの洞窟" }
   elseif( $work.MAP -eq "ve_fild01" ) { $work.MAP = "ベインスフィールド 01" }
   elseif( $work.MAP -eq "ve_fild02" ) { $work.MAP = "ベインスフィールド 02" }
   elseif( $work.MAP -eq "ve_fild03" ) { $work.MAP = "ベインスフィールド 03" }
   elseif( $work.MAP -eq "ve_fild04" ) { $work.MAP = "ベインスフィールド 04" }
   elseif( $work.MAP -eq "ve_fild05" ) { $work.MAP = "ベインスフィールド 05" }
   elseif( $work.MAP -eq "ve_fild06" ) { $work.MAP = "ベインスフィールド 06" }
   elseif( $work.MAP -eq "ve_fild07" ) { $work.MAP = "ベインスフィールド 07" }
   elseif( $work.MAP -eq "1@cash" ) { $work.MAP = "暴窟王の洞窟" }
   elseif( $work.MAP -eq "1@spa" ) { $work.MAP = "亡霊の王宮" }
   elseif( $work.MAP -eq "mal_dun01" ) { $work.MAP = "星明りの珊瑚礁" }
   elseif( $work.MAP -eq "1@xm_d" ) { $work.MAP = "ホラーおもちゃ工場" }
   elseif( $work.MAP -eq "malaya" ) { $work.MAP = "ポートマラヤ" }
   elseif( $work.MAP -eq "1@eom" ) { $work.MAP = "魔神殿" }
   elseif( $work.MAP -eq "1@tnm2" ) { $work.MAP = "魔神の塔最上階" }
   elseif( $work.MAP -eq "1@tnm1" ) { $work.MAP = "魔神の塔上層" }
   elseif( $work.MAP -eq "man_fild01" ) { $work.MAP = "マヌクフィールド 01" }
   elseif( $work.MAP -eq "man_fild02" ) { $work.MAP = "マヌクフィールド 02" }
   elseif( $work.MAP -eq "man_fild03" ) { $work.MAP = "マヌクフィールド 03" }
   elseif( $work.MAP -eq "geffen" ) { $work.MAP = "魔法の都市ゲフェン" }
   elseif( $work.MAP -eq "malangdo" ) { $work.MAP = "マラン島" }
   elseif( $work.MAP -eq "e_tower" ) { $work.MAP = "ミスティーアイランド" }
   elseif( $work.MAP -eq "e_tower" ) { $work.MAP = "ミスティーアイランド" }
   elseif( $work.MAP -eq "mid_camp" ) { $work.MAP = "ミッドガルド連合軍駐屯地" }
   elseif( $work.MAP -eq "alberta" ) { $work.MAP = "港の都市アルベルタ" }
   elseif( $work.MAP -eq "mjolnir_01" ) { $work.MAP = "ミョルニール山脈 01" }
   elseif( $work.MAP -eq "mjolnir_02" ) { $work.MAP = "ミョルニール山脈 02" }
   elseif( $work.MAP -eq "mjolnir_03" ) { $work.MAP = "ミョルニール山脈 03" }
   elseif( $work.MAP -eq "mjolnir_04" ) { $work.MAP = "ミョルニール山脈 04" }
   elseif( $work.MAP -eq "mjolnir_05" ) { $work.MAP = "ミョルニール山脈 05" }
   elseif( $work.MAP -eq "mjolnir_06" ) { $work.MAP = "ミョルニール山脈 06" }
   elseif( $work.MAP -eq "mjolnir_07" ) { $work.MAP = "ミョルニール山脈 07" }
   elseif( $work.MAP -eq "mjolnir_08" ) { $work.MAP = "ミョルニール山脈 08" }
   elseif( $work.MAP -eq "mjolnir_09" ) { $work.MAP = "ミョルニール山脈 09" }
   elseif( $work.MAP -eq "mjolnir_10" ) { $work.MAP = "ミョルニール山脈 10" }
   elseif( $work.MAP -eq "mjolnir_11" ) { $work.MAP = "ミョルニール山脈 11" }
   elseif( $work.MAP -eq "mjolnir_12" ) { $work.MAP = "ミョルニール山脈 12" }
   elseif( $work.MAP -eq "mjo_dun01" ) { $work.MAP = "ミョルニール廃鉱 B1F" }
   elseif( $work.MAP -eq "mjo_dun02" ) { $work.MAP = "ミョルニール廃鉱 B2F" }
   elseif( $work.MAP -eq "mjo_dun03" ) { $work.MAP = "ミョルニール廃鉱 B3F" }
   elseif( $work.MAP -eq "prt_maze01" ) { $work.MAP = "迷宮の森 01" }
   elseif( $work.MAP -eq "prt_maze02" ) { $work.MAP = "迷宮の森 02" }
   elseif( $work.MAP -eq "prt_maze03" ) { $work.MAP = "迷宮の森 03" }
   elseif( $work.MAP -eq "moscovia" ) { $work.MAP = "モスコビア" }
   elseif( $work.MAP -eq "mosk_fild02" ) { $work.MAP = "モスコビアフィールド" }
   elseif( $work.MAP -eq "ama_test" ) { $work.MAP = "モモタロ体験館" }
   elseif( $work.MAP -eq "mosk_dun01" ) { $work.MAP = "森" }
   elseif( $work.MAP -eq "1@rev" ) { $work.MAP = "モルスの洞窟" }
   elseif( $work.MAP -eq "moc_ruins" ) { $work.MAP = "モロク - ピラミッド周辺" }
   elseif( $work.MAP -eq "1@tnm3" ) { $work.MAP = "モロク城地下" }
   elseif( $work.MAP -eq "1@ma_h" ) { $work.MAP = "闇のビョンウンゴ病院2階" }
   elseif( $work.MAP -eq "xmas" ) { $work.MAP = "雪の街ルティエ" }
   elseif( $work.MAP -eq "amatsu" ) { $work.MAP = "泉水の国アマツ" }
   elseif( $work.MAP -eq "1@ravi" ) { $work.MAP = "ラヴィーネ山脈01" }
   elseif( $work.MAP -eq "2@ravi" ) { $work.MAP = "ラヴィーネ山脈02" }
   elseif( $work.MAP -eq "lounge01_jp" ) { $work.MAP = "ラウンジ 1F" }
   elseif( $work.MAP -eq "lounge02_jp" ) { $work.MAP = "ラウンジ 2F" }
   elseif( $work.MAP -eq "lounge00_jp" ) { $work.MAP = "ラウンジ B1F" }
   elseif( $work.MAP -eq "moc_para01" ) { $work.MAP = "楽園団 01" }
   elseif( $work.MAP -eq "eclage" ) { $work.MAP = "ラフィネ族の首都 エクラージュ" }
   elseif( $work.MAP -eq "ra_fild01" ) { $work.MAP = "ラヘルフィールド 01（アウドムラ草原）" }
   elseif( $work.MAP -eq "ra_fild02" ) { $work.MAP = "ラヘルフィールド 02（オズ狭谷）" }
   elseif( $work.MAP -eq "ra_fild03" ) { $work.MAP = "ラヘルフィールド 03（イダ平原）" }
   elseif( $work.MAP -eq "ra_fild04" ) { $work.MAP = "ラヘルフィールド 04（アウドムラ草原）" }
   elseif( $work.MAP -eq "ra_fild05" ) { $work.MAP = "ラヘルフィールド 05（アウドムラ草原）" }
   elseif( $work.MAP -eq "ra_fild06" ) { $work.MAP = "ラヘルフィールド 06（ポルトルナ）" }
   elseif( $work.MAP -eq "ra_fild07" ) { $work.MAP = "ラヘルフィールド 07（オズ狭谷）" }
   elseif( $work.MAP -eq "ra_fild08" ) { $work.MAP = "ラヘルフィールド 08（イダ平原）" }
   elseif( $work.MAP -eq "ra_fild09" ) { $work.MAP = "ラヘルフィールド 09（アウドムラ草原）" }
   elseif( $work.MAP -eq "ra_fild10" ) { $work.MAP = "ラヘルフィールド 10（オズ狭谷）" }
   elseif( $work.MAP -eq "ra_fild11" ) { $work.MAP = "ラヘルフィールド 11（イダ平原）" }
   elseif( $work.MAP -eq "ra_fild12" ) { $work.MAP = "ラヘルフィールド 12（イダ平原）" }
   elseif( $work.MAP -eq "ra_fild13" ) { $work.MAP = "ラヘルフィールド 13（涙の海岸）" }
   elseif( $work.MAP -eq "lhz_fild01" ) { $work.MAP = "リヒタルゼンフィールド 01" }
   elseif( $work.MAP -eq "lhz_fild02" ) { $work.MAP = "リヒタルゼンフィールド 02(死神の峡谷)" }
   elseif( $work.MAP -eq "lhz_fild03" ) { $work.MAP = "リヒタルゼンフィールド 03" }
   elseif( $work.MAP -eq "lou_dun01" ) { $work.MAP = "龍之城ダンジョン 01（王陵）" }
   elseif( $work.MAP -eq "lou_dun02" ) { $work.MAP = "龍之城ダンジョン 02（王陵 内部）" }
   elseif( $work.MAP -eq "lou_dun03" ) { $work.MAP = "龍之城ダンジョン 03（白羊宮）" }
   elseif( $work.MAP -eq "lou_fild01" ) { $work.MAP = "龍之城フィールド 01" }
   elseif( $work.MAP -eq "xmas_fild01" ) { $work.MAP = "ルティエフィールド 01" }
   elseif( $work.MAP -eq "prontera" ) { $work.MAP = "ルーンミッドガッツ王国の首都プロンテラ" }
   elseif( $work.MAP -eq "mora" ) { $work.MAP = "レシア族の街 モーラ" }
   elseif( $work.MAP -eq "lhz_in01" ) { $work.MAP = "レッケンベル本社" }
   elseif( $work.MAP -eq "harboro1" ) { $work.MAP = "ロックリッジ" }
   elseif( $work.MAP -eq "rockmi1" ) { $work.MAP = "ロックリッジ鉱山 01" }
   elseif( $work.MAP -eq "rockmi3" ) { $work.MAP = "ロックリッジ鉱山 01 奥地" }
   elseif( $work.MAP -eq "rockmi2" ) { $work.MAP = "ロックリッジ鉱山 02" }
   elseif( $work.MAP -eq "harboro2" ) { $work.MAP = "ロックリッジ地下街" }
   elseif( $work.MAP -eq "harboro3" ) { $work.MAP = "ロックリッジ地下街 奥地" }
   elseif( $work.MAP -eq "que_sign01" ) { $work.MAP = "わからない所" }
   elseif( $work.MAP -eq "1@la_00" ) { $work.MAP = "試練の迷宮" }
   elseif( $work.MAP -eq "1@lb_00" ) { $work.MAP = "封印の迷宮" }
   elseif( $work.MAP -eq "1@lc_00" ) { $work.MAP = "異形の迷宮" }
   elseif( $work.MAP -eq "gef_d01_j" ) { $work.MAP = "250 ページ" }
   elseif( $work.MAP -eq "pay_d03_i" ) { $work.MAP = "月夜花の悪夢" }
   elseif( $work.MAP -eq "ice_d03_i" ) { $work.MAP = "フローズンメモリー"}
} `
}

#############################################################
# GUIで表示
$ro2 | select-object "NAME","count","time","random","MAP","subMAP" | Out-GridView -wait
